import { LaunchStatus } from "../models/instance";
import Button from "./ui/Button";
export default function LaunchErrorHelp({status,language,onRetry,onAccounts,onSettings,onDismiss}:{status:LaunchStatus;language:"en"|"de";onRetry:()=>void;onAccounts:()=>void;onSettings:()=>void;onDismiss:()=>void}){
  if(status.state!=="error")return null;
  const de=language==="de";const text=(en:string,deText:string)=>de?deText:en;const message=status.message.toLowerCase();
  const account=/account|sign.in|login|token/.test(message),network=/download|network|connect|request|dns/.test(message),memory=/memory|heap|ram/.test(message),disk=/disk|space|permission|access.*denied|cannot.*(write|create)/.test(message),cancelled=message.includes("cancel");
  const help=cancelled?text("The operation was cancelled. You can try again when you’re ready.","Der Vorgang wurde abgebrochen. Du kannst ihn jederzeit erneut starten."):account?text("Select an account or sign in again, then launch the instance.","Wähle einen Account oder melde dich erneut an. Starte danach die Instanz."):network?text("Check your connection and retry. Completed files can be reused.","Prüfe deine Verbindung und versuche es erneut. Fertige Dateien können wiederverwendet werden."):memory?text("Check the instance’s memory allocation and close other applications.","Prüfe den zugewiesenen Arbeitsspeicher und schließe andere Anwendungen."):disk?text("Check free space and whether the game folder is writable.","Prüfe den freien Speicherplatz und die Schreibrechte für den Spieleordner."):text("The instance could not start. Retry, or review its version, mod loader and settings.","Die Instanz konnte nicht starten. Versuche es erneut oder prüfe Version, Modloader und Einstellungen.");
  return <section className="launch-help" role="alert"><div><h3>{cancelled?text("Cancelled","Abgebrochen"):text("Let’s get this working","So geht es weiter")}</h3><p>{help}</p><details><summary>{text("Technical details","Technische Details")}</summary><pre>{status.message}</pre></details></div><div className="help-actions"><Button onClick={account?onAccounts:onRetry}>{account?text("Accounts","Accounts"):text("Retry","Erneut versuchen")}</Button><Button variant="secondary" onClick={onSettings}>{text("Settings","Einstellungen")}</Button><Button variant="ghost" onClick={onDismiss}>{text("Dismiss","Schließen")}</Button></div></section>;
}
